# Generated by Django 5.1.6 on 2025-09-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(max_length=200)),
                ('shs_strand', models.CharField(max_length=50)),
                ('tvl_strand', models.CharField(blank=True, max_length=50, null=True)),
                ('interest_science', models.IntegerField()),
                ('interest_arts', models.IntegerField()),
                ('ability_logic', models.IntegerField()),
                ('ability_creativity', models.IntegerField()),
                ('recommended_course_1', models.CharField(blank=True, max_length=200)),
                ('recommended_course_2', models.CharField(blank=True, max_length=200)),
                ('recommended_course_3', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
