# Generated by Django 5.1.6 on 2025-09-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The official name of the course.', max_length=200, unique=True)),
                ('description', models.TextField(help_text='A brief, engaging description of the course.')),
                ('icon', models.CharField(default='book-open', help_text="Name of a Feather icon (e.g., 'cpu', 'pen-tool').", max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='ability_comm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ability_practical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ability_teamwork',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='interest_business',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='interest_design',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='interest_sports',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='interest_teaching',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='interest_tech',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='ability_creativity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='ability_logic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='interest_arts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='interest_science',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Student Name (Optional)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='school',
            field=models.CharField(max_length=200, verbose_name='School/University'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='shs_strand',
            field=models.CharField(max_length=50, verbose_name='SHS Strand'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='tvl_strand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TVL Strand'),
        ),
    ]
