# Generated by Django 5.1.6 on 2025-09-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_course_assessment_ability_comm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='interest_building',
            field=models.IntegerField(default=0, help_text='e.g., engines, electronics'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='interest_helping',
            field=models.IntegerField(default=0, help_text='e.g., advising, caring'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='interest_leading',
            field=models.IntegerField(default=0, help_text='e.g., organizing, managing'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='interest_nature',
            field=models.IntegerField(default=0, help_text='e.g., plants, animals'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='A brief description of the course.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
