# Generated by Django 5.1.6 on 2025-09-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_assessment_interest_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='feedback_rating_1',
            field=models.IntegerField(blank=True, help_text='Rating for the 1st recommendation', null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='feedback_rating_2',
            field=models.IntegerField(blank=True, help_text='Rating for the 2nd recommendation', null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='feedback_rating_3',
            field=models.IntegerField(blank=True, help_text='Rating for the 3rd recommendation', null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='feedback_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='interest_building',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='interest_helping',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='interest_leading',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='interest_nature',
            field=models.IntegerField(default=0),
        ),
    ]
