# Generated by Django 5.1.6 on 2025-10-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='field_category',
            field=models.CharField(choices=[('TECH', 'Technology, Computing, & Data'), ('ENG', 'Engineering, Architecture, & Design'), ('BUS', 'Business, Management, & Economics'), ('HEALTH', 'Health, Life, & Natural Sciences'), ('SOCIAL', 'Social Sciences, Humanities, & Liberal Arts'), ('MEDIA', 'Communication, Media, & Creative Arts'), ('EDUC', 'Education & Library Science'), ('PUB', 'Public Service & Administration'), ('HOSP', 'Hospitality, Tourism, & Service Industries'), ('APPLIED', 'Applied, Technical, & Vocational Sciences')], default='TECH', help_text='The broad category this course belongs to (used for Stage 1 recommendation).', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='top_schools',
            field=models.TextField(blank=True, help_text='Comma-separated list of top schools in Metro Manila for this course.'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='feedback_rating_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='feedback_rating_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='feedback_rating_3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
