# Generated by Django 5.1.6 on 2025-10-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_course_field_category_course_top_schools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='ability_spatial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='interest_detail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='interest_policy',
            field=models.IntegerField(default=0),
        ),
    ]
