# Generated by Django 5.1.6 on 2025-10-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_assessment_ability_spatial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='interest_research',
            field=models.IntegerField(default=0),
        ),
    ]
