# Generated by Django 5.1.6 on 2025-10-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_assessment_interest_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='offering_universities',
            field=models.ManyToManyField(blank=True, related_name='offered_courses', to='recommender.university'),
        ),
    ]
