# Generated by Django 5.1.6 on 2025-10-24 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0009_university_course_offering_universities'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The user-friendly persona label (e.g., 'Logical Problem Solver').", max_length=100, unique=True)),
                ('key_traits_json', models.JSONField(default=list, help_text='JSON list of key traits for weighting.')),
                ('profile_json', models.JSONField(default=dict, help_text='JSON dictionary of ideal trait scores.')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='base_persona_key',
            field=models.CharField(default='Computer Science', help_text='pls.', max_length=100),
        ),
        migrations.AddField(
            model_name='assessment',
            name='custom_trait_scores',
            field=models.TextField(blank=True, help_text='change value.'),
        ),
        migrations.AddField(
            model_name='course',
            name='global_trait_overrides',
            field=models.TextField(blank=True, help_text='Custom trait:score pairs (e.g., ability_logic:5, interest_detail:4) for global fine-tuning.'),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, help_text='Admission process and tuition info.'),
        ),
        migrations.CreateModel(
            name='CoursePersonaWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_factor', models.IntegerField(default=1, help_text="Weight (1-5) to multiply this persona's influence.")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='recommender.course')),
                ('persona_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.personatemplate')),
            ],
            options={
                'unique_together': {('course', 'persona_template')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='active_personas',
            field=models.ManyToManyField(blank=True, help_text='The set of base personas activated for this course with custom weights.', related_name='courses_using_template', through='recommender.CoursePersonaWeight', to='recommender.personatemplate'),
        ),
    ]
