# Generated by Django 5.1.6 on 2025-11-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0011_assessment_ability_abstract_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='ability_not_impulsive',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='interest_clerical',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='interest_environmental',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='interest_mechanical',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='interest_science',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='interest_sports',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='interest_teaching',
        ),
        migrations.AddField(
            model_name='assessment',
            name='ability_comm_written',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ability_negotiation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ability_problem_solve',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='dmgt_flexibility',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='dmgt_initiative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='dmgt_integrity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='dmgt_stress_manage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='base_persona_key',
            field=models.CharField(default='Computer Science', help_text='Internal key for the base persona, if applicable.', max_length=100),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='custom_trait_scores',
            field=models.TextField(blank=True, help_text='Raw input data from assessment.'),
        ),
    ]
