# Generated by Django 5.1.6 on 2025-11-12 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0012_remove_assessment_ability_not_impulsive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('strand', models.CharField(choices=[('STEM', 'STEM'), ('ABM', 'ABM'), ('HUMSS', 'HUMSS'), ('GAS', 'GAS'), ('TVL', 'TVL'), ('COLLEGE', 'College/University'), ('PROFESSIONAL', 'Professional/Graduate')], default='COLLEGE', max_length=50)),
                ('university', models.CharField(blank=True, max_length=200, verbose_name='School/University')),
                ('year_level', models.CharField(choices=[('11', 'Grade 11'), ('12', 'Grade 12'), ('1', '1st Year College'), ('2', '2nd Year College'), ('3', '3rd Year College'), ('4', '4th Year College'), ('GRAD', 'Graduate/Post-grad')], default='1', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
