# Generated by Django 5.1.6 on 2025-11-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='last_completed_step',
            field=models.IntegerField(default=0),
        ),
    ]
