# Generated by Django 5.1.6 on 2025-11-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0015_profilechangetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='strand',
            field=models.CharField(choices=[('STEM', 'STEM'), ('ABM', 'ABM'), ('HUMSS', 'HUMSS'), ('GAS', 'GAS'), ('TVL', 'TVL')], default='COLLEGE', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year_level',
            field=models.CharField(choices=[('11', 'Grade 11'), ('12', 'Grade 12')], default='1', max_length=10),
        ),
    ]
