# Generated by Django 5.1.6 on 2025-11-13 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0016_alter_userprofile_strand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='name',
        ),
        migrations.AddField(
            model_name='assessment',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Student Name (Snapshot)'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
